# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd3e736ac6548d5d4b5a83c9bef868e8a8c34234298924493aaceecd2c1a4a83c8d2c105437db2c3f756f0becfbfa1015b96d86191183cc30a714531e1a1abd

test:
  secret_key_base: e93602fd5606b33b3572e581e65a1141407f187413957cd7702c87b9056fcbde314bf713a1bf1fe1555cc8890a6e0c2f3bc5b3a05ff75a66bd057535c7a7ab86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
